#use_frameworks!
source 'https://cdn.cocoapods.org/' #source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Yodo1Games/MAS-Spec.git'
source 'https://github.com/Yodo1Games/Yodo1Spec.git'

platform :ios, '9.0'
inhibit_all_warnings!
target "Runner" do

pod 'Yodo1MasFull', '4.3.0'

end
